let Categorias = [
    {
      id: 0,
      name: "Bandas",
      icon: "bx-music",
    },
]

let Trabajos = [
    {
      id: 0,
      title: "Queen",
      desc: "Queen es una banda británica de rock formada en 1970 en Londres, integrada por Freddie Mercury, Brian May, Roger Taylor y John Deacon.",
      link: "https://tp02-armeno-dawidowicz.netlify.app/",
      date: "7/6/2023",
      curso: "4IC",
      author: "Armeno - Dawidowicz",
      img: "Assets/Images/Bandas/armeno-dawidowicz.webp",
      category: "Bandas",
    },
    {
      id: 1,
      title: "Soda Stereo",
      desc: "Soda Stereo es una banda del Rock alternativo formada en Buenos Aires, Argentina en 1982 por Gustavo Cerati, Zeta Bosio y Charly Alberti",
      link: "https://tp02-cottet-lewin.netlify.app/",
      date: "7/6/2023",
      curso: "4IC",
      author: "Cottet - Lewin",
      img: "Assets/Images/Bandas/cottet-lewin.webp",
      category: "Bandas",
    },
    {
      id: 2,
      title: "Tan Bionica",
      desc: "Tan Biónica es un grupo musical argentino surgido en Buenos Aires en el año 2002 formado por Chano, Seby, Bambi y Diega.",
      link: "https://tp02-kupersmid-izbicki.netlify.app/",
      date: "7/6/2023",
      curso: "4IC",
      author: "Kupersmid - Izbicki",
      img: "Assets/Images/Bandas/kupersmid-izbicki.webp",
      category: "Bandas",
    },
    {
      id: 3,
      title: "Marama",
      desc: "Márama es un grupo musical uruguayo de cumbia pop, formado en 2014.",
      link: "https://tp2htmlcss.netlify.app/",
      date: "7/6/2023",
      curso: "4IC",
      author: "Chmielevsky - Naccache",
      img: "Assets/Images/Bandas/chmielevsky-naccache.webp",
      category: "Bandas",
    },
    {
      id: 4,
      title: "Los Piojos",
      desc: "Los Piojos fue un grupo musical de Argentina formado a fines del año 1988, en la Ciudad Jardín Lomas del Palomar, en la zona oeste del Gran Buenos Aires.",
      link: "https://stunning-biscuit-2d7af6.netlify.app/",
      date: "7/6/2023",
      curso: "4IC",
      author: "Ramasso - Dominguez",
      img: "Assets/Images/Bandas/ramasso-dominguez.webp",
      category: "Bandas",
    },
    {
      id: 5,
      title: "The Beatles",
      desc: "The Beatles, también conocida en el mundo hispano como los Beatles, fue una banda de rock británica formada en Liverpool durante los años 1960.",
      link: "https://tp02html-biderman-szabo-giraudi.netlify.app/",
      date: "7/6/2023",
      curso: "4IC",
      author: "Biderman - Szabo - Giraudi",
      img: "Assets/Images/Bandas/biderman-szabo-giraudi.webp",
      category: "Bandas",
    },
    {
      id: 6,
      title: "Queen",
      desc: "Queen es una banda británica de rock formada en 1970 en Londres, integrada por Freddie Mercury, Brian May, Roger Taylor y John Deacon.",
      link: "https://tp2gajercohen.netlify.app/",
      date: "7/6/2023",
      curso: "4IC",
      author: "Gajer - Cohen",
      img: "Assets/Images/Bandas/gajer-cohen.webp",
      category: "Bandas",
    },
    {
      id: 7,
      title: "Coldplay",
      desc: "Coldplay es una banda británica formada en Londres en 1997. Está compuesto por 5 integrantes: Chris Martin, Jonny Buckland, Guy Berryman, Will Champion y Phil Harvey.​",
      link: "https://tp2brunsteinkaltman.netlify.app/",
      date: "7/6/2023",
      curso: "4IC",
      author: "Brunstein - Kaltman",
      img: "Assets/Images/Bandas/brunstein-kaltman.webp",
      category: "Bandas",
    },
  ];
  
  export { Categorias, Trabajos };